CREATE ROLE togglin
WITH
  LOGIN PASSWORD 'togglin';

\c togglin_local

GRANT CONNECT ON DATABASE togglin_local TO togglin;
GRANT USAGE ON SCHEMA public TO togglin;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO togglin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO togglin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES to togglin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS to togglin;
