services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: togglin_local
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - togglin_network
    volumes:
      - togglin_db_data:/var/lib/postgresql/data/pgdata
      - ./scripts/entrypoints/local-db-init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  togglin_db_data:

networks:
  togglin_network:
    driver: bridge
